version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
    - ./mvnw clean package
  post_build:
    commands:
    - echo $(basename ./target/*.jar)
    - pwd

cache:
  paths:
  - '/root/.m2/**/*'