version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
    - mvn clean install
  post_build:
    commands:
    - echo $(basename ./target/*.jar)
    - pwd
artifacts:
  files:
  - target/running-0.0.1-SNAPSHOT.jar
cache:
  paths:
  - '/root/.m2/**/*'