debug: false
server:
  servlet:
    session:
      timeout: 1m
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  security:
    user:
      name: user
      password: passowrd
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


